server:
  port: 8080

spring:
  application:
    name: spring-messenger-server
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://arch-acer.local:5432/edu_alexey_messenger
    username: postgres
    password: gfhjkm%J{J{J
    
     
#  datasource:
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: sa
#    url: jdbc:h2:file:./data
#  h2:
#    # http://localhost:port/h2-console
#    console:
#      enabled: true
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
#    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      '[hibernate.jdbc.time_zone]': UTC
      '[hibernate.current_session_context_class]': org.springframework.orm.hibernate5.SpringSessionContext
      '[hibernate.show_sql]': true
      '[hibernate.format_sql]': true
      '[hibernate.highlight_sql]': true
#      '[javax.persistence.create-database-schemas]': true
#      '[javax.persistence.schema-generation.database.action]': create



logging:
  file: 
    name: ./logs/app.log
  logback:
    rollingpolicy:
      clean-history-on-start: true
  level:
    web: info
    '[logging.level.org.hibernate.orm.jdbc.bind]': trace
  pattern:
    console: "%clr(%d{HH:mm}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(%25.25logger{0}){cyan} %clr(:){faint} %m%n%wEx"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operations-sorter: method
    