server:
  port: 8080

spring:
  application:
    name: spring-messenger-server
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      '[hibernate.jdbc.time_zone]': UTC
      '[hibernate.current_session_context_class]': org.springframework.orm.hibernate5.SpringSessionContext
      '[hibernate.show_sql]': true
      '[hibernate.format_sql]': true
      '[hibernate.highlight_sql]': true
#      '[javax.persistence.create-database-schemas]': true
#      '[javax.persistence.schema-generation.database.action]': create

logging:
  file: 
    name: ./logs/app.log
  logback:
    rollingpolicy:
      clean-history-on-start: true
  level:
    web: info
    '[logging.level.org.hibernate.orm.jdbc.bind]': trace
  pattern:
    console: "%clr(%d{HH:mm}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(%25.25logger{0}){cyan} %clr(:){faint} %m%n%wEx"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operations-sorter: method
    